apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: hippo2-chaos
  namespace: pgo
spec:
  appinfo:
    appns: 'pgo'
    applabel: 'name=hippo'
    appkind: 'deployment'
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
  chaosServiceAccount: pod-delete-sa
  # It can be delete/retain
  jobCleanUpPolicy: 'retain'
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '90'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '30'
              
            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: 'true'
